[project]
name = "jxbayesian"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "blackjax>=1.3",
    "jax[cuda13]>=0.8.1",
    "numpyro>=0.19.0",
    "optax>=0.2.6",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "jupyter-cache>=1.0.1",
    "ptpython>=3.0.32",
]
