[project]
name = "rayai"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ray[data,serve,train,tune]>=2.52.0",
]

[dependency-groups]
dev = [
    "basedpyright>=1.34.0",
    "mcp>=1.22.0",
    "ptpython>=3.0.32",
    "ruff>=0.14.6",
]
