[project]
name = "jx"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "jax[cuda13]>=0.8.1",
]

[dependency-groups]
dev = [
    "basedpyright>=1.34.0",
    "jupyter>=1.1.1",
    "jupyter-cache>=1.0.1",
    "ruff>=0.14.6",
]
