[project]
name = "jx"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "jax[cuda]>=0.8.1",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "jupyter-cache>=1.0.1",
    "ptpython>=3.0.32",
]
