[project]
name = "pt"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "torch>=2.9.1",
    "torchaudio>=2.9.1",
    "torchvision>=0.24.1",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "jupyter-cache>=1.0.1",
    "ptpython>=3.0.32",
]
